### ISSUE TITLE
import user script error

### ISSUE THREAD

**Issue by clburlison** [GR360RY/snipeit-ansible#7]
Alright, finally had a change to play around with your AD user import script. I am running this manually for the time being but I'm running into an error.

```bash
Traceback (most recent call last):
  File "./import_ad_users.py", line 67, in <module>
    get_ldap_users()
  File "./import_ad_users.py", line 41, in get_ldap_users
    email = user[ldap_attributes['email']][0]
  File "/usr/local/lib/python2.7/dist-packages/ldapdict/ldapdict.py", line 405, in __getitem__
    raise KeyError(key)
KeyError: 'mail'
```  

I have modified the LDAP settings and credentials to what I believe are the correct values for my environment. Do you have any troubleshooting ideas? Are there some python requirements that I might be missing? (python noob here)

**Comment by clburlison** [comment]
Closing old issues. This was resolved a while back.
